/*
 * Copyright 2022-2026 Crown Copyright
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package sleeper.clients.deploy.documentation;

import io.swagger.v3.core.util.Yaml;
import io.swagger.v3.oas.models.Components;
import io.swagger.v3.oas.models.OpenAPI;
import io.swagger.v3.oas.models.PathItem;
import io.swagger.v3.oas.models.Paths;
import io.swagger.v3.oas.models.SpecVersion;
import io.swagger.v3.oas.models.info.Info;
import io.swagger.v3.oas.models.media.ObjectSchema;
import io.swagger.v3.oas.models.media.Schema;
import io.swagger.v3.oas.models.media.StringSchema;
import io.swagger.v3.oas.models.security.SecurityRequirement;
import io.swagger.v3.oas.models.security.SecurityScheme;
import io.swagger.v3.oas.models.servers.Server;
import io.swagger.v3.oas.models.servers.ServerVariable;
import io.swagger.v3.oas.models.servers.ServerVariables;

import sleeper.restapi.RestApiLambda;
import sleeper.restapi.Route;

import java.io.IOException;
import java.nio.file.Files;
import java.nio.file.Path;
import java.util.List;

/**
 * Generates the OpenAPI spec at {@code docs/rest-api/openapi.yaml} by walking the REST API's route registry and
 * asking each route to describe itself. The committed spec is the output of this main; do not hand-edit it — update
 * the route's {@code openApi*} methods and rerun {@code scripts/dev/generateDocumentation.sh}.
 */
public class GenerateOpenApiSpec {

    private static final String OUTPUT_PATH = "docs/rest-api/openapi.yaml";
    private static final String HEADER = "# Auto-generated by sleeper.clients.deploy.documentation.GenerateOpenApiSpec.\n" +
            "# Do not edit by hand. Update the route's openApi* methods and rerun scripts/dev/generateDocumentation.sh.\n";
    private static final String SIGV4_SCHEME_NAME = "sigv4";

    private GenerateOpenApiSpec() {
    }

    public static void main(String[] args) throws IOException {
        Path output = Path.of(args[0]).resolve(OUTPUT_PATH);
        OpenAPI spec = buildSpec();
        Files.writeString(output, HEADER + Yaml.pretty(spec));
    }

    static OpenAPI buildSpec() {
        OpenAPI spec = new OpenAPI(SpecVersion.V30)
                .openapi("3.0.3")
                .info(new Info()
                        .title("Sleeper REST API")
                        .description("REST API for interacting with a deployed Sleeper instance. Provisioned by the " +
                                "optional `RestApiStack` and fronted by an AWS API Gateway v2 HTTP API. All requests " +
                                "must be signed with AWS SigV4; callers need the `execute-api:Invoke` permission on " +
                                "the API. See docs/rest-api/README.md for deployment, authentication and worked " +
                                "examples.")
                        .version("0.1.0"))
                .servers(List.of(new Server()
                        .url("https://{apiId}.execute-api.{region}.amazonaws.com")
                        .description("The invoke URL of a deployed Sleeper REST API. The full URL is exposed as the " +
                                "CDK output `RestApiUrl` and as the instance property `sleeper.rest.api.url`.")
                        .variables(new ServerVariables()
                                .addServerVariable("apiId", new ServerVariable()
                                        ._default("abcd1234")
                                        .description("The API Gateway HTTP API id (the subdomain in the invoke URL)."))
                                .addServerVariable("region", new ServerVariable()
                                        ._default("eu-west-2")
                                        .description("The AWS region the Sleeper instance is deployed in.")))))
                .security(List.of(new SecurityRequirement().addList(SIGV4_SCHEME_NAME)))
                .components(new Components()
                        .addSecuritySchemes(SIGV4_SCHEME_NAME, sigv4SecurityScheme())
                        .addSchemas("Error", errorSchema()))
                .paths(new Paths());

        for (Route route : RestApiLambda.buildRoutes(null, null).values()) {
            PathItem pathItem = spec.getPaths().computeIfAbsent(route.openApiPath(), k -> new PathItem());
            pathItem.operation(route.openApiMethod(), route.openApiOperation());
            route.openApiSchemas().forEach(spec.getComponents()::addSchemas);
        }

        return spec;
    }

    private static SecurityScheme sigv4SecurityScheme() {
        SecurityScheme scheme = new SecurityScheme()
                .type(SecurityScheme.Type.APIKEY)
                .name("Authorization")
                .in(SecurityScheme.In.HEADER)
                .description("AWS Signature Version 4. Required by the API Gateway v2 IAM authorizer. Callers must " +
                        "have an IAM identity with `execute-api:Invoke` on the API. The AWS SDKs and tools such as " +
                        "`awscurl` sign requests automatically.");
        scheme.addExtension("x-amazon-apigateway-authtype", "awsSigv4");
        return scheme;
    }

    private static Schema<?> errorSchema() {
        return new ObjectSchema()
                .required(List.of("error"))
                .addProperty("error", new StringSchema()
                        .description("A short, stable identifier for the error. Known values include " +
                                "`invalid_request`, `table_already_exists`, `not_found`, and `internal_error`."))
                .addProperty("message", new StringSchema()
                        .description("A human-readable description of the failure. May be absent."));
    }
}
