name: "owasp-dep-scan"
description: "dep-scan is a fully open-source security audit tool for project dependencies based on known vulnerabilities and advisories."
inputs:
  src:
    description: "Source directory to scan. Defaults to workspace"
    required: false
    default: "/github/workspace"
  reportsDir:
    description: "Output directory for the generated reports. Defaults to ./reports"
    required: false
    default: "/github/workspace/reports"
  profile:
    description: "Name of the profile to use (appsec, research, operational, threat-modeling, license-compliance, generic)"
    required: false
    default: "generic"
  projectType:
    description: "Type of project"
    required: false
    default: "unknown"

runs:
  using: "docker"
  image: "docker://ghcr.io/owasp-dep-scan/dep-scan:release-5.x"
  args:
    - "--src"
    - ${{ inputs.src }}
    - "--reports-dir"
    - ${{ inputs.reportsDir }}
    - "--profile"
    - ${{ inputs.profile }}
    - "--type"
    - ${{ inputs.projectType }}
    - "--debug"
    - "--explain"
branding:
  icon: "check"
  color: "blue"