/*
 * Copyright 2022-2025 Crown Copyright
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package sleeper.systemtest.cdk;

import software.amazon.awscdk.App;
import software.amazon.awscdk.AppProps;
import software.amazon.awscdk.Environment;
import software.amazon.awscdk.StackProps;
import software.amazon.awssdk.services.s3.S3Client;

import sleeper.cdk.jars.SleeperJarsInBucket;
import sleeper.cdk.stack.SleeperInstanceStack;
import sleeper.cdk.util.CdkContext;
import sleeper.cdk.util.Utils;
import sleeper.core.deploy.DeployInstanceConfiguration;
import sleeper.core.properties.instance.InstanceProperties;
import sleeper.systemtest.configuration.SystemTestProperties;

import static sleeper.core.properties.instance.CommonProperty.ACCOUNT;
import static sleeper.core.properties.instance.CommonProperty.ID;
import static sleeper.core.properties.instance.CommonProperty.REGION;
import static sleeper.systemtest.configuration.SystemTestProperty.SYSTEM_TEST_CLUSTER_ENABLED;

/**
 * Deploys Sleeper and additional stacks used for large-scale system tests.
 */
public class SystemTestApp extends SleeperInstanceStack {
    private final SleeperJarsInBucket jars;
    private final SystemTestProperties properties;

    public SystemTestApp(App app, String id, StackProps props, DeployInstanceConfiguration configuration, SleeperJarsInBucket jars) {
        super(app, id, props, configuration, jars);
        this.jars = jars;
        this.properties = SystemTestProperties.from(configuration.getInstanceProperties());
    }

    @Override
    public void create() {

        generateLoggingStack();

        generateAutoDeleteS3ObjectsStack();

        // System test bucket needs to be created first so that it's listed as an ingest source bucket before the ingest
        // stacks are created.
        SystemTestBucketStack bucketStack = new SystemTestBucketStack(this, "SystemTestIngestBucket", properties, jars, getAutoDeleteS3ObjectsStack());

        // Control which stacks are generated by sleeperCDKApp.
        setGenerateLoggingStack(false);
        setGenerateAutoDeleteS3ObjectsStack(false);
        setGenerateProperties(false);

        // super.create() is here as the system test stacks need to be created first, before creating the rest of the stack.
        super.create();
        // Stack for writing random data
        if (properties.getBoolean(SYSTEM_TEST_CLUSTER_ENABLED)) {
            new SystemTestClusterStack(this, "SystemTest", properties, bucketStack,
                    getAutoStopEcsClusterTasksStack());
        }

        setGenerateProperties(true);
        generateProperties();
    }

    public static void main(String[] args) {
        App app = new App(AppProps.builder()
                .analyticsReporting(false)
                .build());

        DeployInstanceConfiguration configuration = Utils.loadDeployInstanceConfiguration(CdkContext.from(app));
        InstanceProperties instanceProperties = configuration.getInstanceProperties();

        String id = instanceProperties.get(ID);
        Environment environment = Environment.builder()
                .account(instanceProperties.get(ACCOUNT))
                .region(instanceProperties.get(REGION))
                .build();

        try (S3Client s3Client = S3Client.create()) {
            SleeperJarsInBucket jars = SleeperJarsInBucket.from(s3Client, instanceProperties);

            new SystemTestApp(app, id, StackProps.builder()
                    .stackName(id)
                    .env(environment)
                    .build(),
                    configuration, jars).create();

            app.synth();
        }
    }
}
