[build-system]
requires = ["setuptools>=80"]
build-backend = "setuptools.build_meta"

[project]
name = "sleeper"
version = "0.37.2.dev1"
description = "Python client for Sleeper"
requires-python = ">=3.10"

dependencies = [
    "pyarrow",
    "boto3",
    "s3fs",
    "boto3-stubs[essential]",
    "websockets",
    "jproperties",
]

classifiers = [
    "Development Status :: 4 - Beta",
    "Intended Audience :: Developers",
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3.10",
    "Programming Language :: Python :: 3.11",
    "Programming Language :: Python :: 3.12",
    "Programming Language :: Python :: 3.13",
    "Programming Language :: Python :: 3.14",
    "Typing :: Typed",
]

[project.optional-dependencies]
dev = [
    "ruff",
    "pytest",
    "pytest-mock",
    "pytest-asyncio",
    "testcontainers[localstack]",
]

[tool.setuptools]
package-dir = {"" = "src"}

[tool.setuptools.packages.find]
where = ["src"]

[tool.setuptools.package-data]
sleeper = ["py.typed"]

[tool.pytest.ini_options]
addopts = [
    "--import-mode=importlib",
]
python_functions = "should_*"
filterwarnings = [
    "error",
    "default::DeprecationWarning",
]

[tool.ruff]
line-length = 200
