[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[tool.pytest.ini_options]
addopts = [
    "--import-mode=importlib",
]
python_functions = "should_*"
filterwarnings = [
    "error",
    "default::DeprecationWarning",
]

[tool.ruff]
line-length = 200
