[SERVICE]
    Flush        5
    Log_Level    info
    Parsers_File /fluent-bit/etc/parsers.conf
@INCLUDE /fluent-bit/etc/input.conf
@INCLUDE /fluent-bit/etc/filters.conf
@INCLUDE /fluent-bit/etc/output.conf
