
vulnerabilities:
  # You can suppress known vulnerabilities here like this:
  # - id: CVE-2000-12345

  # Vulnerabilties in AWS Lambda RIE due to an old version of Golang standard library
  - id: CVE-2025-61726
  - id: CVE-2025-61728
  - id: CVE-2025-61730
  - id: CVE-2025-68121
