
vulnerabilities:

  # Dependencies of the latest version of Docker:

  # Golang stdlib
  - id: CVE-2026-32280
  - id: CVE-2026-32281
  - id: CVE-2026-32282
  - id: CVE-2026-32283
  - id: CVE-2026-32288
  - id: CVE-2026-32289
  # github.com/docker/docker
  - id: CVE-2026-34040
  - id: CVE-2026-33997
  # go.opentelemetry.io/otel
  - id: CVE-2026-29181
  # go.opentelemetry.io/otel/exporters/otlp/otlpmetric/otlpmetrichttp
  # go.opentelemetry.io/otel/exporters/otlp/otlptrace/otlptracehttp
  - id: CVE-2026-39882
  # go.opentelemetry.io/otel/sdk
  - id: CVE-2026-39883
  # sigstore/timestamp-authority
  - id: CVE-2026-39984
  # moby/spdystream
  - id: CVE-2026-35469

