
vulnerabilities:
  # You can suppress known vulnerabilities here like this:
  # - id: CVE-2000-12345

  # See GitHub issue for Jetty vulnerabilities: https://github.com/gchq/sleeper/issues/8043

  #  org.eclipse.jetty:jetty-security
  - id: CVE-2026-10050
  #  org.eclipse.jetty:jetty-server
  - id: CVE-2026-6790


  # Trivy is saying Jackson 2.22.2 is present in images, but Maven reports only 2.22.3 is used. This may be a temporary
  # problem in GitHub Actions.

  # com.fasterxml.jackson.core:jackson-databind
  - id: CVE-2026-91776
  - id: CVE-2026-91777
