
# This ignore file is only used for the Docker image used for bulk import in EKS. This is an experimental feature.
# Normally bulk import is done in EMR, where we run a jar rather than a Docker image.

# This image is based on Spark's Docker image, and we match the version of Spark used by EMR. Because this is an older
# version, it includes a number of vulnerabilities.

vulnerabilities:
  # Apps installed in Ubuntu

  # bind9-host, bind9-libs
  - id: CVE-2025-40778
  - id: CVE-2025-40780
  - id: CVE-2025-8677

  # Java dependencies in Spark

  # com.fasterxml.jackson.core:jackson-core
  # (hadoop-client-runtime-3.4.1.jar)
  - id: CVE-2025-52999
  - id: CVE-2025-49128
  # com.google.guava:guava
  # (spark-network-common_2.12-3.5.6.jar)
  - id: CVE-2018-10237
  - id: CVE-2023-2976
  - id: CVE-2020-8908
  # com.nimbusds:nimbus-jose-jwt
  # (hadoop-client-runtime-3.4.1.jar)
  - id: CVE-2025-53864
  # commons-beanutils:commons-beanutils
  # (hadoop-client-runtime-3.4.1.jar)
  - id: CVE-2025-48734
  # org.apache.avro:avro
  # (hadoop-client-runtime-3.4.1.jar)
  - id: CVE-2024-47561
  - id: CVE-2023-39410
  - id: CVE-2025-33042
  # org.apache.commons:commons-lang3
  # (hadoop-client-runtime-3.4.1.jar)
  - id: CVE-2025-48924
  # org.eclipse.jetty:jetty-http
  # (bulk-import-runner.jar)
  # (hadoop-client-runtime-3.4.1.jar)
  # (spark-core_2.12-3.5.6.jar)
  - id: CVE-2024-6763
  # org.eclipse.jetty:jetty-server
  # (spark-core_2.12-3.5.6.jar)
  - id: CVE-2024-13009
  # org.lz4:lz4-java
  # (lz4-java-1.8.0.jar)
  - id: CVE-2025-12183
