
vulnerabilities:

  # Dependencies of the latest version of Docker:

  ## Golang
  # stdlib
  - id: CVE-2026-39821
  - id: CVE-2026-46600
  - id: CVE-2026-56859
  - id: CVE-2026-56860
  - id: CVE-2026-56853
  - id: CVE-2026-56858
  - id: CVE-2026-56862
  - id: CVE-2026-33818
  # github.com/docker/docker
  - id: CVE-2026-34040
  - id: CVE-2026-33997
  # golang.org/x/mod
  - id: CVE-2026-56864
  - id: CVE-2026-56865
  # golang.org/x/net
  - id: CVE-2026-46600
  # github.com/cilium/ebpf
  - id: CVE-2026-10722
  # github.com/moby/go-archive
  - id: CVE-2026-17106

  # AWS SDK supports supports up to version 24.x of node.js. Therefore are unable to update for issue below
  # until support is provided.
  ## Node.js (node-pkg)
  # brace-expansion
  - id: CVE-2026-14257
  - id: CVE-2026-69152
  # ip-address
  - id: CVE-2026-54272
  - id: CVE-2026-69192
  - id: CVE-2026-69198
  # tar
  - id: GHSA-r292-9mhp-454m
  - id: CVE-2026-73566
  # undici
  - id: CVE-2026-16728
  - id: CVE-2026-16729
  - id: CVE-2026-15157
