
# This ignore file is only used for the Docker image used for bulk import in EKS. This is an experimental feature.
# Normally bulk import is done in EMR, where we run a jar rather than a Docker image.

# This image is based on Spark's Docker image, and we match the version of Spark used by EMR. Because this is an older
# version, it includes a number of vulnerabilities.

vulnerabilities:
  # Apps installed in Ubuntu

  # bind9-host, bind9-libs
  - id: CVE-2025-40778
  - id: CVE-2025-40780
  - id: CVE-2025-8677
  # binutils, binutils-common, binutils-x86-64-linux-gnu, libbinutils, libctf-nobfd0, libctf0
  - id: CVE-2024-57360
  - id: CVE-2025-0840
  - id: CVE-2025-11082
  - id: CVE-2025-11083
  - id: CVE-2025-11412
  - id: CVE-2025-11413
  - id: CVE-2025-11414
  - id: CVE-2025-1147
  - id: CVE-2025-1148
  - id: CVE-2025-11494
  - id: CVE-2025-1176
  - id: CVE-2025-1178
  - id: CVE-2025-1181
  - id: CVE-2025-1182
  - id: CVE-2025-11839
  - id: CVE-2025-11840
  - id: CVE-2025-3198
  - id: CVE-2025-5244
  - id: CVE-2025-5245
  - id: CVE-2025-7545
  - id: CVE-2025-8225
  - id: CVE-2025-1153
  # dirmngr
  - id: CVE-2025-30258
  # dpkg
  - id: CVE-2025-6297
  # gcc-12-base
  - id: CVE-2025-6297
  # gnupg
  - id: CVE-2025-30258
  # krb5-user, libgssapi-krb5-2, libgssrpc4, libkadm5clnt-mit12, libkadm5srv-mit12, libkdb5-10, libkrb5-3, libkrb5support0
  - id: CVE-2025-24528
  - id: CVE-2025-3576
  - id: CVE-2024-26458
  - id: CVE-2024-26461
  # libc-bin, libc6, locales
  - id: CVE-2025-0395
  - id: CVE-2025-4802
  - id: CVE-2025-8058
  # libcap2
  - id: CVE-2025-1390
  # libexpat1
  - id: CVE-2024-8176
  # libfreetype6
  - id: CVE-2025-27363
  # libgcc-s1, libstdc++6
  - id: CVE-2023-4039
  # libgnutls30
  - id: CVE-2024-12243
  - id: CVE-2025-32988
  - id: CVE-2025-32989
  - id: CVE-2025-32990
  - id: CVE-2025-6395
  # libk5crypto3
  - id: CVE-2024-3596
  # libpam-modules, libpam-modules-bin, libpam-runtime, libpam0g
  - id: CVE-2025-6020
  # libpng16-16
  - id: CVE-2025-64505
  - id: CVE-2025-64506
  - id: CVE-2025-64720
  - id: CVE-2025-65018
  # libsqlite3-0
  - id: CVE-2025-29088
  - id: CVE-2025-6965
  # libssh-4
  - id: CVE-2025-4877
  - id: CVE-2025-4878
  - id: CVE-2025-5318
  - id: CVE-2025-5372
  - id: CVE-2025-8114
  # libssl3, openssl
  - id: CVE-2025-9230
  - id: CVE-2024-13176
  - id: CVE-2024-9143
  # libsystemd0, libudev1
  - id: CVE-2025-4598
  # libtasn1-6
  - id: CVE-2024-12133
  # libxml2
  - id: CVE-2025-32414
  - id: CVE-2025-32415
  - id: CVE-2025-49794
  - id: CVE-2025-49796
  - id: CVE-2025-6021
  - id: CVE-2025-6170
  - id: CVE-2025-7425
  - id: CVE-2025-9714
  # net-tools
  - id: CVE-2025-46836
  # perl-base
  - id: CVE-2024-56406
  - id: CVE-2025-40909

  # Java dependencies in Spark

  # com.fasterxml.jackson.core:jackson-core
  # (hadoop-client-runtime-3.4.1.jar)
  - id: CVE-2025-52999
  - id: CVE-2025-49128
  # com.google.guava:guava
  # (spark-network-common_2.12-3.5.6.jar)
  - id: CVE-2018-10237
  - id: CVE-2023-2976
  - id: CVE-2020-8908
  # com.nimbusds:nimbus-jose-jwt
  # (hadoop-client-runtime-3.4.1.jar)
  - id: CVE-2025-53864
  # commons-beanutils:commons-beanutils
  # (hadoop-client-runtime-3.4.1.jar)
  - id: CVE-2025-48734
  # org.apache.avro:avro
  # (hadoop-client-runtime-3.4.1.jar)
  - id: CVE-2024-47561
  - id: CVE-2023-39410
  # org.apache.commons:commons-lang3
  # (hadoop-client-runtime-3.4.1.jar)
  - id: CVE-2025-48924
  # org.eclipse.jetty:jetty-http
  # (bulk-import-runner.jar)
  # (hadoop-client-runtime-3.4.1.jar)
  # (spark-core_2.12-3.5.6.jar)
  - id: CVE-2024-6763
  # org.eclipse.jetty:jetty-server
  # (spark-core_2.12-3.5.6.jar)
  - id: CVE-2024-13009
  # org.lz4:lz4-java
  # (lz4-java-1.8.0.jar)
  - id: CVE-2025-12183
