services:
  localstack:
    image: localstack/localstack:4.2
    container_name: sleeper-localstack
    ports:
      - "4566:4566"
      - "9000:9000"
    environment:
      - SERVICES=s3,dynamodb,sqs
      - PERSISTENCE=/tmp/localstack/data
      - LAMBDA_EXECUTOR=local
      - DOCKER_HOST=unix:///var/run/docker.sock
      - START_WEB=1
