name: Depscan
on:
  workflow_call:
    inputs:
      path:
        required: true
        type: string
      projectType:
        required: false
        type: string
        default: "unknown"

jobs:
  dep-scan:
    runs-on: ubuntu-latest
    steps:
      - name: Delete unnecessary tools folders
        run: |
          rm -rf /opt/hostedtoolcache
          rm -rf /usr/share/dotnet
          rm -rf /opt/ghc
          rm -rf "/usr/local/share/boost"
          rm -rf "$AGENT_TOOLSDIRECTORY"
      - uses: actions/checkout@v3
      - name: Get current date
        id: date
        run: echo "date=$(date +'%Y-%m-%d')" >> $GITHUB_OUTPUT
      - name: Cache VDB home
        uses: actions/cache@v4
        with:
          path: ${{ github.workspace }}/vdb
          key: ${{ runner.os }}-dep-scan-${{ steps.date.outputs.date }}
          restore-keys: |
            ${{ runner.os }}-dep-scan-
      - name: Run dep-scan
        uses: ./.github/actions/dep-scan
        with:
          src: /github/workspace/${{ inputs.path }}
          projectType: ${{ inputs.projectType }}
        env:
          VDB_HOME: ${{ github.workspace }}/vdb
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - uses: actions/upload-artifact@v4
        with:
          name: Upload reports
          path: reports
