name: Docker CLI Deployment
on:
  workflow_dispatch: # Allow manual running
  schedule: # Planned execution once per day
    - cron: "30 1 * * *"
  push:
    branches:
      - develop
    paths:
      - '.github/workflows/docker-cli-branch.yaml'
      - '.github/workflows/docker-cli.yaml'
      - '.github/workflows/docker-cli-image.yaml'
      - '.github/scripts/planCliBuild.sh'
      - 'scripts/cli/**'

jobs:
  build-cli:
    uses: ./.github/workflows/docker-cli.yaml
    with:
      pushImages: ${{ github.repository_owner == 'gchq' }}
