name: Python Tests
on:
  pull_request:
    paths:
      - 'python/**'
      - '.github/workflows/python-tests.yaml'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.13'
      - name: Make venv
        run: |
          python -m venv "${GITHUB_WORKSPACE}/python/env"
          echo PATH=${GITHUB_WORKSPACE}/python/env/bin:$PATH >> $GITHUB_ENV
      - name: Python build
        run: pip install .
        working-directory: ./python
      - name: Python tests
        run: pytest
        working-directory: ./python
