name: Python Tests
on:
  pull_request:
    paths:
      - 'python/**'
      - '.github/workflows/python-tests.yaml'

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
        - python-version: "3.12"
          experimental: false
        - python-version: "3.13"
          experimental: true
        - python-version: "3.14"
          experimental: true

    continue-on-error: ${{ matrix.experimental }}
    steps:
      - uses: actions/checkout@v6
      - uses: actions/setup-python@v6
        with:
          python-version: ${{ matrix.python-version }}
          cache: 'pip'
      - name: Python build
        run: pip install --editable ".[dev]"
        working-directory: ./python
      - name: Python tests
        run: pytest
        working-directory: ./python
