name: Python Lint
on:
  pull_request:
    paths:
      - 'python/**'
      - '.github/workflows/python-lint.yaml'

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.10", "3.11", "3.12", "3.13", "3.14"]

    steps:
      - uses: actions/checkout@v7
      - uses: actions/setup-python@v7
        with:
          python-version: ${{ matrix.python-version }}
          cache: 'pip'
      - name: Python build
        run: pip install ".[dev]"
        working-directory: ./python
      - name: Ruff check
        run: ruff check
        working-directory: ./python
      - name: Ruff format check
        run: ruff format --check
        working-directory: ./python
